const bibliotecaMangas = {
    "Francis_X_Raikou": [
        "https://files.catbox.moe/43ktnl.webp",
        "https://files.catbox.moe/0wvop6.webp",
        "https://files.catbox.moe/2ea43v.webp",
        "https://files.catbox.moe/4jeiwb.webp",
        "https://files.catbox.moe/k641on.webp",
        "https://files.catbox.moe/45iwtf.webp",
        "https://files.catbox.moe/xcmwxd.webp",
        "https://files.catbox.moe/fxp6w4.webp",
        "https://files.catbox.moe/iui6ib.webp",
        "https://files.catbox.moe/e59x3c.webp",
        "https://files.catbox.moe/hof5ld.webp",
        "https://files.catbox.moe/ufd6vy.webp",
        "https://files.catbox.moe/3cxwjb.webp",
        "https://files.catbox.moe/htzu6j.webp",
        "https://files.catbox.moe/3kbpnc.webp",
        "https://files.catbox.moe/czlv70.webp",
        "https://files.catbox.moe/zbul4h.webp",
        "https://files.catbox.moe/4gexlr.webp",
        "https://files.catbox.moe/bt64f6.webp",
        "https://files.catbox.moe/g0kz4b.webp",
        "https://files.catbox.moe/lsvrwb.webp",
        "https://files.catbox.moe/ylhrrv.webp",
        "https://files.catbox.moe/c9f1f7.webp"
    ],
    "Yang_Gui_Fei_X_Prota": [],
    "Ibuki_X_Yui": [],
    "BB_X_Prota": [],
    "Jalter_X_Apocrypha_NPC": [],
    "Futanarijima_ch1": [],
    "Futanarijima_ch2": [],
    "Futanarijima_ch3": [],
    "Futanarijima_ch4": [],
    "Futanarijima_ch5": [],
    "Futanarijima_ch6": []
};
